import { Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className="antialiased"
      >
        <main className={`${roboto.variable} ${geistMono.variable}`}>
          {children}
          <Toaster richColors closeButton />
        </main>
      </body>
    </html>
  );
}
